# Generated by Django 3.2.9 on 2021-11-04 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.groupmodel')),
                ('group_Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_Admin', to=settings.AUTH_USER_MODEL)),
                ('requested_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
