# Generated by Django 3.2.9 on 2021-11-11 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0002_requestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='activityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=300)),
                ('number_of_sets', models.CharField(max_length=300)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.groupmodel')),
            ],
        ),
    ]
