# Generated by Django 3.2.9 on 2021-11-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_rename_added_on_activitymodel_activity_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymodel',
            name='activity_added_on',
        ),
    ]
