# Generated by Django 3.2.9 on 2021-11-12 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_remove_activitymodel_activity_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymodel',
            name='activity_added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
